package br.com.dblinks.thundera;

import br.com.dblinks.thundera.actions.config.ScreenshotConfig;
import br.com.dblinks.thundera.config.ApplicationConfig;
import br.com.dblinks.thundera.navigator.Navigator;
import br.com.dblinks.thundera.navigator.page.URL;
import javax.enterprise.event.Observes;
import javax.inject.Inject;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jboss.weld.environment.se.events.ContainerInitialized;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.firefox.MarionetteDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.opera.OperaDriver;

public class FrmInicial extends javax.swing.JFrame {

    @Inject
    private ApplicationConfig applicationConfig;

    @Inject
    private ScreenshotConfig screenshotConfig;

    @Inject
    private Navigator navigator;

    public void start(@Observes ContainerInitialized event) {
        java.awt.EventQueue.invokeLater(() -> {
            initComponents();

            ImageIcon icon = new ImageIcon(getClass().getResource("/thundera.ico"));
            setIconImage(icon.getImage());

            setLocationRelativeTo(null);
            setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDominio = new javax.swing.JPanel();
        txtDominio = new javax.swing.JTextField();
        btnGerar = new javax.swing.JButton();
        pnlScreenshots = new javax.swing.JPanel();
        chk1920x1080 = new javax.swing.JCheckBox();
        chk1280x720 = new javax.swing.JCheckBox();
        chk1024x768 = new javax.swing.JCheckBox();
        chk768x1024 = new javax.swing.JCheckBox();
        chk600x1024 = new javax.swing.JCheckBox();
        chk375x667 = new javax.swing.JCheckBox();
        chk667x375 = new javax.swing.JCheckBox();
        chk320x480 = new javax.swing.JCheckBox();
        chk480x320 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        chkRecursiva = new javax.swing.JCheckBox();
        pnlJobs = new javax.swing.JPanel();
        txtJobs = new javax.swing.JSpinner();
        pnlNavegadores = new javax.swing.JPanel();
        chkChrome = new javax.swing.JCheckBox();
        chkFirefox = new javax.swing.JCheckBox();
        chkOpera = new javax.swing.JCheckBox();
        chkInternetExplorer = new javax.swing.JCheckBox();
        chkEdge = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thundera");
        setResizable(false);

        pnlDominio.setBorder(javax.swing.BorderFactory.createTitledBorder("Domínio"));
        pnlDominio.setToolTipText("");
        pnlDominio.setName(""); // NOI18N

        javax.swing.GroupLayout pnlDominioLayout = new javax.swing.GroupLayout(pnlDominio);
        pnlDominio.setLayout(pnlDominioLayout);
        pnlDominioLayout.setHorizontalGroup(
            pnlDominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDominioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDominio)
                .addContainerGap())
        );
        pnlDominioLayout.setVerticalGroup(
            pnlDominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDominioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        pnlScreenshots.setBorder(javax.swing.BorderFactory.createTitledBorder("Screenshots"));

        chk1920x1080.setSelected(true);
        chk1920x1080.setText("1920 x 1080");

        chk1280x720.setSelected(true);
        chk1280x720.setText("1280 x 720");

        chk1024x768.setSelected(true);
        chk1024x768.setText("1024 x 768");

        chk768x1024.setText("768 x 1024");

        chk600x1024.setText("600 x 1024");

        chk375x667.setText("375 x 667");

        chk667x375.setText("667 x 375");

        chk320x480.setText("320 x 480");

        chk480x320.setText("480 x 320");

        javax.swing.GroupLayout pnlScreenshotsLayout = new javax.swing.GroupLayout(pnlScreenshots);
        pnlScreenshots.setLayout(pnlScreenshotsLayout);
        pnlScreenshotsLayout.setHorizontalGroup(
            pnlScreenshotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScreenshotsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlScreenshotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chk1920x1080, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(chk1280x720, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chk1024x768, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chk768x1024, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chk600x1024, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chk375x667, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chk667x375, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chk320x480, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chk480x320, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlScreenshotsLayout.setVerticalGroup(
            pnlScreenshotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScreenshotsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chk1920x1080)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk1280x720)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk1024x768)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk768x1024)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk600x1024)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk375x667)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk667x375)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk320x480)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk480x320)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Navegação"));

        chkRecursiva.setText("Recursiva");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkRecursiva, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkRecursiva)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlJobs.setBorder(javax.swing.BorderFactory.createTitledBorder("Jobs"));

        txtJobs.setValue(1);

        javax.swing.GroupLayout pnlJobsLayout = new javax.swing.GroupLayout(pnlJobs);
        pnlJobs.setLayout(pnlJobsLayout);
        pnlJobsLayout.setHorizontalGroup(
            pnlJobsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJobsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtJobs, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlJobsLayout.setVerticalGroup(
            pnlJobsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJobsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtJobs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlNavegadores.setBorder(javax.swing.BorderFactory.createTitledBorder("Navegadores"));

        chkChrome.setSelected(true);
        chkChrome.setText("Chrome");

        chkFirefox.setText("Firefox");

        chkOpera.setText("Opera");

        chkInternetExplorer.setText("Internet Explorer");

        chkEdge.setText("Edge");

        javax.swing.GroupLayout pnlNavegadoresLayout = new javax.swing.GroupLayout(pnlNavegadores);
        pnlNavegadores.setLayout(pnlNavegadoresLayout);
        pnlNavegadoresLayout.setHorizontalGroup(
            pnlNavegadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavegadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNavegadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkChrome, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(chkFirefox, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(chkOpera, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(chkInternetExplorer, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(chkEdge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlNavegadoresLayout.setVerticalGroup(
            pnlNavegadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavegadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkChrome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkFirefox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkOpera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkInternetExplorer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkEdge)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDominio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlScreenshots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlNavegadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlJobs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDominio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlScreenshots, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNavegadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlJobs, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        if (txtDominio.getText().length() < 1) {
            return;
        }

        // Host
        applicationConfig.setHost(txtDominio.getText());

        // Resoluções
        if (chk1920x1080.isSelected()) {
            screenshotConfig.addDimension(new Dimension(1920, 1080));
        }
        if (chk1280x720.isSelected()) {
            screenshotConfig.addDimension(new Dimension(1280, 720));
        }
        if (chk1024x768.isSelected()) {
            screenshotConfig.addDimension(new Dimension(1024, 768));
        }
        if (chk768x1024.isSelected()) {
            screenshotConfig.addDimension(new Dimension(768, 1024));
        }
        if (chk600x1024.isSelected()) {
            screenshotConfig.addDimension(new Dimension(600, 1024));
        }
        if (chk375x667.isSelected()) {
            screenshotConfig.addDimension(new Dimension(375, 667));
        }
        if (chk667x375.isSelected()) {
            screenshotConfig.addDimension(new Dimension(667, 375));
        }
        if (chk320x480.isSelected()) {
            screenshotConfig.addDimension(new Dimension(320, 480));
        }
        if (chk480x320.isSelected()) {
            screenshotConfig.addDimension(new Dimension(480, 320));
        }

        // Navegador
        if (chkChrome.isSelected()) {
            applicationConfig.addDriver(ChromeDriver.class);
        }
        if (chkFirefox.isSelected()) {
            applicationConfig.addDriver(MarionetteDriver.class);
        }
        if (chkOpera.isSelected()) {
            applicationConfig.addDriver(OperaDriver.class);
        }
        if (chkInternetExplorer.isSelected()) {
            applicationConfig.addDriver(InternetExplorerDriver.class);
        }
        if (chkEdge.isSelected()) {
            applicationConfig.addDriver(EdgeDriver.class);
        }

        // Navegação recursiva
        applicationConfig.setRecursive(chkRecursiva.isSelected());

        // Número de jobs
        applicationConfig.setMaxJobs(Integer.parseInt(txtJobs.getValue().toString()));

        navigator.navigate(new URL(txtDominio.getText()));
        JOptionPane.showMessageDialog(this, "Relatório finalizado com sucesso!");

    }//GEN-LAST:event_btnGerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JCheckBox chk1024x768;
    private javax.swing.JCheckBox chk1280x720;
    private javax.swing.JCheckBox chk1920x1080;
    private javax.swing.JCheckBox chk320x480;
    private javax.swing.JCheckBox chk375x667;
    private javax.swing.JCheckBox chk480x320;
    private javax.swing.JCheckBox chk600x1024;
    private javax.swing.JCheckBox chk667x375;
    private javax.swing.JCheckBox chk768x1024;
    private javax.swing.JCheckBox chkChrome;
    private javax.swing.JCheckBox chkEdge;
    private javax.swing.JCheckBox chkFirefox;
    private javax.swing.JCheckBox chkInternetExplorer;
    private javax.swing.JCheckBox chkOpera;
    private javax.swing.JCheckBox chkRecursiva;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlDominio;
    private javax.swing.JPanel pnlJobs;
    private javax.swing.JPanel pnlNavegadores;
    private javax.swing.JPanel pnlScreenshots;
    private javax.swing.JTextField txtDominio;
    private javax.swing.JSpinner txtJobs;
    // End of variables declaration//GEN-END:variables
}
